# Site settings
title: lbr.
short_logo: lbr.
description: >
  Engineering, DevOps & Cloud Computing
baseurl: "" 
url: "https://leebriggs.co.uk" 

author:
  fullname: Lee Briggs
  github: /jaxxstorm
  linkedin: /briggsl
  email: /contact@leebriggs.co.uk

g_track_id: UA-34865189-1

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
highlighter: none

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true
      listed: true
      author: Lee Briggs
      author_link: <a href="https://leebriggs.co.uk/">Lee Briggs<a>
